# Generated by Django 5.2.7 on 2025-10-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20251013_2043'),
    ]

    operations = [
        # Сначала обновляем существующие записи с NULL created_at
        migrations.RunSQL(
            "UPDATE store_game SET created_at = '2024-01-01 00:00:00' WHERE created_at IS NULL;",
            reverse_sql="UPDATE store_game SET created_at = NULL WHERE created_at = '2024-01-01 00:00:00';"
        ),
        migrations.RunSQL(
            "UPDATE store_game SET updated_at = '2024-01-01 00:00:00' WHERE updated_at IS NULL;",
            reverse_sql="UPDATE store_game SET updated_at = NULL WHERE updated_at = '2024-01-01 00:00:00';"
        ),
        # Теперь делаем поле non-nullable
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Добавляем новые поля в Purchase
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Банковская карта'), ('points', 'Очки')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='card_number',
            field=models.CharField(blank=True, help_text='Номер карты (заглушка)', max_length=19),
        ),
        migrations.AddField(
            model_name='purchase',
            name='card_holder',
            field=models.CharField(blank=True, help_text='Владелец карты (заглушка)', max_length=100),
        ),
        # Создаем новые модели
        migrations.CreateModel(
            name='RouletteGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, help_text='Стоимость одного вращения', max_digits=10)),
                ('probability', models.FloatField(default=1.0, help_text='Вероятность выпадения (0.0-1.0)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Игра рулетки',
                'verbose_name_plural': 'Игры рулетки',
            },
        ),
        migrations.CreateModel(
            name='RouletteSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.roulettegame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('won_game', models.ForeignKey(blank=True, help_text='Выигранная игра', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roulette_wins', to='store.game')),
            ],
            options={
                'verbose_name': 'Вращение рулетки',
                'verbose_name_plural': 'Вращения рулетки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouletteAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('attempts_used', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Попытка рулетки',
                'verbose_name_plural': 'Попытки рулетки',
            },
        ),
        migrations.AddConstraint(
            model_name='rouletteattempt',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date'),
        ),
    ]
