# Generated by Django 5.2.7 on 2025-10-20 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20251020_1809'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_at'], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.RemoveConstraint(
            model_name='rouletteattempt',
            name='unique_user_date',
        ),
        migrations.AddField(
            model_name='roulettegame',
            name='prizes',
            field=models.ManyToManyField(blank=True, help_text='Игры, которые выпадают в этой рулетке', related_name='available_in_roulettes', to='store.game'),
        ),
        migrations.AlterField(
            model_name='roulettespin',
            name='won_game',
            field=models.ForeignKey(blank=True, help_text='Выигранная игра', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.game'),
        ),
        migrations.AlterUniqueTogether(
            name='rouletteattempt',
            unique_together={('user', 'date')},
        ),
    ]
