# Generated by Django 5.2.7 on 2025-10-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='incorrect_answers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
